builds:
    - env:
          - CGO_ENABLED=0
      goos:
          - linux
          - darwin
      goarch:
          - amd64
          - arm64
      main: ./cmd/main.go

archives:
    - files:
          - sandboxes/*
          - codapi.json
          - codapi.service
          - LICENSE
